### ISSUE TITLE
这个好用吗？

### ISSUE THREAD

**Issue by HotBitmapGG** [yanjiabin/ExtendDialog#1]
有没有在商业项目中使用过，有没有什么问题呢，用起来有什么坑吗？

**Comment by HotBitmapGG** [comment]
@yanjiabin

**Comment by yanjiabin** [comment]
我公司的项目都是用的这个.方便的很,所以才分享出来

**Comment by HotBitmapGG** [comment]
@yanjiabin 你是哪家公司的  我是武汉老司机科技有限公司的，对你很有兴趣，最近有换工作的打算吗？
